# makefile for Camera

# (C) Bill Lenhart 

CLASS = SinTranslateNodeGL
PROGS = $(CLASS)Test
USESCLASSES = ../NodeGL/NodeGL.o ../MaterialNodeGL/MaterialNodeGL.o \
../TransformMaker/TransformMaker.o

include ../include.mak













