# makefile for MaterialNodeGL

# (C) Anonymous1 
# modified Tom White 

CLASS = TransformNodeGL
PROGS = $(CLASS)Test
USESCLASSES = ../NodeGL/NodeGL.o ../functions/functions.o

include ../include.mak













