# makefile for MaterialNodeGL

# (C) Bill Lenhart 
# modified Tom White 

CLASS = OrientNodeGL
PROGS = $(CLASS)Test
USESCLASSES = ../NodeGL/NodeGL.o ../functions/functions.o

include ../include.mak













