# makefile for LightNodeGL

# (C) Bill Lenhart 
# modified Tom White 

CLASS = LightNodeGL
PROGS = $(CLASS)Test
USESCLASSES = ../NodeGL/NodeGL.o ../functions/functions.o

include ../include.mak













