# makefile for MaterialNodeGL

# (C) Anonymous1 
# modified Tom White 

CLASS = Scene
PROGS = $(CLASS)Test
USESCLASSES = ../NodeGL/NodeGL.o ../MaterialNodeGL/MaterialNodeGL.o \
../PlanetNodeGL/PlanetNodeGL.o ../Camera/Camera.o \
../functions/functions.o ../Ray/Ray.o \
../TransformMaker/TransformMaker.o ../LightNodeGL/LightNodeGL.o \
../TransformNodeGL/TransformNodeGL.o ../PopNodeGL/PopNodeGL.o \
../OrbitNodeGL/OrbitNodeGL.o ../SpinNodeGL/SpinNodeGL.o \
../OrientNodeGL/OrientNodeGL.o ../TorusNodeGL/TorusNodeGL.o \
../TeapotNodeGL/TeapotNodeGL.o ../CubeNodeGL/CubeNodeGL.o \
../IcosahedronNodeGL/IcosahedronNodeGL.o \
../OctahedronNodeGL/OctahedronNodeGL.o \
../TetrahedronNodeGL/TetrahedronNodeGL.o \
../DodecahedronNodeGL/DodecahedronNodeGL.o \
../ConeNodeGL/ConeNodeGL.o \
../RotateNodeGL/RotateNodeGL.o \
../SinTranslateNodeGL/SinTranslateNodeGL.o \
../SinSpinNodeGL/SinSpinNodeGL.o \
../CustomNodeGL/CustomNodeGL.o \
../IdentityNodeGL/IdentityNodeGL.o \
../FunTranslateNodeGL/FunTranslateNodeGL.o \
../FunOrientNodeGL/FunOrientNodeGL.o \
../FunTransformNodeGL/FunTransformNodeGL.o \
../FunParser/FunParser.o \
../FunNode/FunNode.o \
../VarFunNode/VarFunNode.o \
../SumFunNode/SumFunNode.o \
../PowFunNode/PowFunNode.o \
../MultFunNode/MultFunNode.o \
../DivFunNode/DivFunNode.o \
../SinFunNode/SinFunNode.o \
../CosFunNode/CosFunNode.o \
../NumFunNode/NumFunNode.o 

include ../include.mak













