# makefile for Camera

# (C) Anonymous1 

CLASS = CustomNodeGL
PROGS = $(CLASS)Test
USESCLASSES = ../NodeGL/NodeGL.o ../MaterialNodeGL/MaterialNodeGL.o \
../TransformMaker/TransformMaker.o

include ../include.mak













